receivers:
  otlp:
    protocols:
      grpc:
      http:

  filelog:
    include:
      - /var/telemetry-logs/*.log
    start_at: beginning
    include_file_path: true
    operators:
      - type: json_parser
        parse_from: body
        timestamp:
          parse_from: attributes.timestamp
          layout: "%Y-%m-%dT%H:%M:%S.%fZ"
        severity:
          parse_from: attributes.severity

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512

  batch:
    send_batch_size: 1024
    timeout: 2s

  resource/common:
    attributes:
      - key: deployment.environment
        value: poc
        action: upsert
      - key: service.namespace
        value: openobserve-poc
        action: upsert

exporters:
  otlphttp/openobserve_traces:
    endpoint: https://openobserve.dylanp.nl/api/3BTUvLGWaJI6cc5tC2JGlZTW1ea
    headers:
      Authorization: Basic a2xhbnRAa2xhbnQubmw6WVJ6YmlJSXVuMndIeUJYWQ==
      stream-name: poc-traces

  otlphttp/openobserve_metrics:
    endpoint: https://openobserve.dylanp.nl/api/3BTUvLGWaJI6cc5tC2JGlZTW1ea
    headers:
      Authorization: Basic a2xhbnRAa2xhbnQubmw6WVJ6YmlJSXVuMndIeUJYWQ==
      stream-name: poc-metrics

  otlphttp/openobserve_logs:
    endpoint: https://openobserve.dylanp.nl/api/3BTUvLGWaJI6cc5tC2JGlZTW1ea
    headers:
      Authorization: Basic a2xhbnRAa2xhbnQubmw6WVJ6YmlJSXVuMndIeUJYWQ==
      stream-name: poc-logs

extensions:
  health_check:

service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - resource/common
        - batch
      exporters:
        - otlphttp/openobserve_traces

    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - resource/common
        - batch
      exporters:
        - otlphttp/openobserve_metrics

    logs:
      receivers:
        - otlp
        - filelog
      processors:
        - memory_limiter
        - resource/common
        - batch
      exporters:
        - otlphttp/openobserve_logs
